# Generated by Django 4.2.2 on 2023-07-11 17:19

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner',
            field=models.ForeignKey(blank=True, help_text='Banner image (<sizing guide>)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='introheader',
            field=models.CharField(default='SKYGAP', max_length=254),
        ),
        migrations.AddField(
            model_name='homepage',
            name='landscape_image',
            field=models.ForeignKey(blank=True, help_text='Landscape image on homepage. (Preferably a product image)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='square_image_left',
            field=models.ForeignKey(blank=True, help_text='Square image on homepage. (Preferably a design image)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='square_image_right',
            field=models.ForeignKey(blank=True, help_text='Square image on homepage. (Preferably a design image)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subheader',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
