# Generated by Django 4.2.2 on 2023-07-17 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('products', '0002_remove_product_colors_remove_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='primary_thumbnail',
            field=models.ForeignKey(blank=True, help_text='Primary Thumbnail Image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_thumbnail',
            field=models.ForeignKey(blank=True, help_text='Secondary Thumbnail Image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
