# Generated by Django 4.2.2 on 2023-07-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_alter_design_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='image',
        ),
    ]
